### ISSUE TITLE
test result

### ISSUE THREAD

**Issue by hu8813** [gwolf-011235/push_swap#1]
hi Gabriel,
tested with https://github.com/hu8813/tester_push_swap

valgrind ./push_swap ""
Memory error

 ./push_swap 5 3 1 2 4 6  | ./checker_linux 5 3 1 2 4 6 
KO

**Comment by gwolf-011235** [comment]
Hi,
thank you!

I was debugging today fixed some stuff. I had some errors in the simple sorts, which are now fixed. 

I also had the weirdest bug with my checker: my push_swap is kinda slow with its output, since it sorts and then prints. When I ran push_swap with my checker, everything was fine. But if i ran "valgrind push_swap | checker", the checker was reading and push_swap was not finished with printing the command! So checker was reading "p" from the printed "pa". Should be fixed now.

Thanks to your checker it sped up the debugging! :D
